version: '3.3'
services:
  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
    networks:
      - core
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka
    networks:
      - core
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - core
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - core
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: seech
      MONGO_INITDB_ROOT_PASSWORD: sechien
      MONGO_INITDB_DATABASE: twitter
    networks:
      - core
networks:
  core:
