version: '2'
services:
  kafka-lenses-dev:
    image: landoop/kafka-lenses-dev
    container_name: kafka-lenses-dev
    ports:
      - "9092:9092"
      - "2181:2181"
      - "8081:8081"
      - "9581:9581"
      - "9582:9582"
      - "9584:9584"
      - "9585:9585"
      - "3030:3030"
    environment:
      EULA: "https://dl.lenses.stream/d/?id=48c8183c-759c-40bb-be70-35311dd146b0"
      ADV_HOST: 127.0.0.1
      SAMPLEDATA: 0
  solr:
    container_name: solr
    image: solr:7.1.0
    ports:
     - "8983:8983"
     - "8984:8984"
    volumes:
     - ./solrconfigsets:/opt/solr/server/solr/configs
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - core
  zoo:
    image: zookeeper
    container_name: zoo
    restart: always
    hostname: zoo
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888
    networks:
      - core

networks:
  core:
