version: '2'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.1'
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
     - "9200:9200"
     - "9300:9300"
    networks:
       - core
  rabbitmq:
     image: 'bitnami/rabbitmq:latest'
     container_name: rabbitmq
     ports:
       - '5672:5672'
       - '15672:15672'
     networks:
       - core

networks:
  core:
